require("catppuccin").setup({
	flavour = "mocha",
	transparent_background = true,
	term_colors = true,
	dim_inactive = {
		enabled = false,
		shade = "dark",
		percentage = 0.15,
	},
	styles = {
		comments = { "italic" },
		conditionals = { "italic" },
		loops = { "italic" },
		functions = {},
		keywords = { "italic" },
		strings = {},
		variables = {},
		numbers = {},
		booleans = {},
		properties = {},
		types = { "italic" },
		operators = {},
	},
	integrations = {
		blink_cmp = true,
		gitsigns = true,
		lsp_trouble = true,
		mason = true,
		native_lsp = {
			enabled = true,
		},
		neotest = true,
		nvimtree = true,
		telescope = {
			enabled = true,
		},
		treesitter = true,
		which_key = true,
	},
})
