#!/bin/zsh
# vim: filetype=sh

#### COLOR UTILS ####
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

#### EDIT AND SOURCE SHORTUTS ####
alias ebash="nvim ~/.bashrc"
alias sbash="source ~/.bashrc"
alias ezsh="nvim ~/.zshrc"
alias szsh="source ~/.zshrc"
alias edotfiles="nvim ~/.aliases"
alias edot="edotfiles"

#### EMACS ALIASES ####
alias e="emacsclient -nc"
alias em="emacsclient -n"
alias et="emacsclient -nw"
alias emacs="~/.local/bin/emacs"
# emacs daemon
alias emd="emacs --daemon"
# emacs kill
alias emk="killall Emacs && killall emacs"

export ALTERNATE_EDITOR=""
export EDITOR="nvim"          # $EDITOR opens in GUI mode
export VISUAL="nvim" # $VISUAL opens in GUI mode

#### NVIM ALIASES ####
alias v="nvim"
alias vi="nvim"
alias nv="nvim"

#### ZELLIJ ALIASES ####
alias zj="zellij"

#### PROGRAM RELATED ####
alias xs="iex -S mix phx.server"
alias mdc="mix do deps.get, compile"
# install from root phoenix app 
alias mpm="npm --prefix assets"
# find mix route
findr () {
  mix phx.routes | grep "$1" | awk '{
    if (NF > 0) {
        printf "%-40s %-7s %-75s %-30s\n", $1, $2, $3, $4;
    }
}'}

# Docker related
alias dcu="docker-compose up -d"
alias dc="docker-compose"

# Command-line related
alias lsa='ls -a'
alias personal="cd ~/repos/_personal"
alias personal="cd ~/repos/_projects"
alias proj="cd ~/repos/_projects/anor"
alias pfind="lsof -i"

### Asdf Updating nvim ###
alias update-nvim-stable='asdf uninstall neovim stable && asdf install neovim stable'
alias update-nvim-nightly='asdf uninstall neovim nightly && asdf install neovim nightly'
alias update-nvim-master='asdf uninstall neovim ref:master && asdf install neovim ref:master'
